<?php
/**
 * ProjectAnalytics
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * RankVectors API
 *
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins.
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ProjectAnalytics Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProjectAnalytics implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProjectAnalytics';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'implementation_stats' => '\OpenAPI\Client\Model\ProjectAnalyticsImplementationStats',
        'suggestion_stats' => '\OpenAPI\Client\Model\ProjectAnalyticsSuggestionStats',
        'sync_stats' => '\OpenAPI\Client\Model\ProjectAnalyticsSyncStats',
        'content_stats' => '\OpenAPI\Client\Model\ProjectAnalyticsContentStats',
        'top_source_pages' => 'object[]',
        'top_target_pages' => 'object[]',
        'orphaned_pages' => 'object[]',
        'high_performing_pages' => 'object[]',
        'most_suggested_pages' => 'object[]',
        'most_linked_to_pages' => 'object[]',
        'recent_implementations' => '\OpenAPI\Client\Model\Implementation[]',
        'recent_suggestions' => '\OpenAPI\Client\Model\Suggestion[]',
        'recent_syncs' => 'object[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'implementation_stats' => null,
        'suggestion_stats' => null,
        'sync_stats' => null,
        'content_stats' => null,
        'top_source_pages' => null,
        'top_target_pages' => null,
        'orphaned_pages' => null,
        'high_performing_pages' => null,
        'most_suggested_pages' => null,
        'most_linked_to_pages' => null,
        'recent_implementations' => null,
        'recent_suggestions' => null,
        'recent_syncs' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'implementation_stats' => false,
        'suggestion_stats' => false,
        'sync_stats' => false,
        'content_stats' => false,
        'top_source_pages' => false,
        'top_target_pages' => false,
        'orphaned_pages' => false,
        'high_performing_pages' => false,
        'most_suggested_pages' => false,
        'most_linked_to_pages' => false,
        'recent_implementations' => false,
        'recent_suggestions' => false,
        'recent_syncs' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'implementation_stats' => 'implementationStats',
        'suggestion_stats' => 'suggestionStats',
        'sync_stats' => 'syncStats',
        'content_stats' => 'contentStats',
        'top_source_pages' => 'topSourcePages',
        'top_target_pages' => 'topTargetPages',
        'orphaned_pages' => 'orphanedPages',
        'high_performing_pages' => 'highPerformingPages',
        'most_suggested_pages' => 'mostSuggestedPages',
        'most_linked_to_pages' => 'mostLinkedToPages',
        'recent_implementations' => 'recentImplementations',
        'recent_suggestions' => 'recentSuggestions',
        'recent_syncs' => 'recentSyncs'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'implementation_stats' => 'setImplementationStats',
        'suggestion_stats' => 'setSuggestionStats',
        'sync_stats' => 'setSyncStats',
        'content_stats' => 'setContentStats',
        'top_source_pages' => 'setTopSourcePages',
        'top_target_pages' => 'setTopTargetPages',
        'orphaned_pages' => 'setOrphanedPages',
        'high_performing_pages' => 'setHighPerformingPages',
        'most_suggested_pages' => 'setMostSuggestedPages',
        'most_linked_to_pages' => 'setMostLinkedToPages',
        'recent_implementations' => 'setRecentImplementations',
        'recent_suggestions' => 'setRecentSuggestions',
        'recent_syncs' => 'setRecentSyncs'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'implementation_stats' => 'getImplementationStats',
        'suggestion_stats' => 'getSuggestionStats',
        'sync_stats' => 'getSyncStats',
        'content_stats' => 'getContentStats',
        'top_source_pages' => 'getTopSourcePages',
        'top_target_pages' => 'getTopTargetPages',
        'orphaned_pages' => 'getOrphanedPages',
        'high_performing_pages' => 'getHighPerformingPages',
        'most_suggested_pages' => 'getMostSuggestedPages',
        'most_linked_to_pages' => 'getMostLinkedToPages',
        'recent_implementations' => 'getRecentImplementations',
        'recent_suggestions' => 'getRecentSuggestions',
        'recent_syncs' => 'getRecentSyncs'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('implementation_stats', $data ?? [], null);
        $this->setIfExists('suggestion_stats', $data ?? [], null);
        $this->setIfExists('sync_stats', $data ?? [], null);
        $this->setIfExists('content_stats', $data ?? [], null);
        $this->setIfExists('top_source_pages', $data ?? [], null);
        $this->setIfExists('top_target_pages', $data ?? [], null);
        $this->setIfExists('orphaned_pages', $data ?? [], null);
        $this->setIfExists('high_performing_pages', $data ?? [], null);
        $this->setIfExists('most_suggested_pages', $data ?? [], null);
        $this->setIfExists('most_linked_to_pages', $data ?? [], null);
        $this->setIfExists('recent_implementations', $data ?? [], null);
        $this->setIfExists('recent_suggestions', $data ?? [], null);
        $this->setIfExists('recent_syncs', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['implementation_stats'] === null) {
            $invalidProperties[] = "'implementation_stats' can't be null";
        }
        if ($this->container['suggestion_stats'] === null) {
            $invalidProperties[] = "'suggestion_stats' can't be null";
        }
        if ($this->container['sync_stats'] === null) {
            $invalidProperties[] = "'sync_stats' can't be null";
        }
        if ($this->container['content_stats'] === null) {
            $invalidProperties[] = "'content_stats' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets implementation_stats
     *
     * @return \OpenAPI\Client\Model\ProjectAnalyticsImplementationStats
     */
    public function getImplementationStats()
    {
        return $this->container['implementation_stats'];
    }

    /**
     * Sets implementation_stats
     *
     * @param \OpenAPI\Client\Model\ProjectAnalyticsImplementationStats $implementation_stats implementation_stats
     *
     * @return self
     */
    public function setImplementationStats($implementation_stats)
    {
        if (is_null($implementation_stats)) {
            throw new \InvalidArgumentException('non-nullable implementation_stats cannot be null');
        }
        $this->container['implementation_stats'] = $implementation_stats;

        return $this;
    }

    /**
     * Gets suggestion_stats
     *
     * @return \OpenAPI\Client\Model\ProjectAnalyticsSuggestionStats
     */
    public function getSuggestionStats()
    {
        return $this->container['suggestion_stats'];
    }

    /**
     * Sets suggestion_stats
     *
     * @param \OpenAPI\Client\Model\ProjectAnalyticsSuggestionStats $suggestion_stats suggestion_stats
     *
     * @return self
     */
    public function setSuggestionStats($suggestion_stats)
    {
        if (is_null($suggestion_stats)) {
            throw new \InvalidArgumentException('non-nullable suggestion_stats cannot be null');
        }
        $this->container['suggestion_stats'] = $suggestion_stats;

        return $this;
    }

    /**
     * Gets sync_stats
     *
     * @return \OpenAPI\Client\Model\ProjectAnalyticsSyncStats
     */
    public function getSyncStats()
    {
        return $this->container['sync_stats'];
    }

    /**
     * Sets sync_stats
     *
     * @param \OpenAPI\Client\Model\ProjectAnalyticsSyncStats $sync_stats sync_stats
     *
     * @return self
     */
    public function setSyncStats($sync_stats)
    {
        if (is_null($sync_stats)) {
            throw new \InvalidArgumentException('non-nullable sync_stats cannot be null');
        }
        $this->container['sync_stats'] = $sync_stats;

        return $this;
    }

    /**
     * Gets content_stats
     *
     * @return \OpenAPI\Client\Model\ProjectAnalyticsContentStats
     */
    public function getContentStats()
    {
        return $this->container['content_stats'];
    }

    /**
     * Sets content_stats
     *
     * @param \OpenAPI\Client\Model\ProjectAnalyticsContentStats $content_stats content_stats
     *
     * @return self
     */
    public function setContentStats($content_stats)
    {
        if (is_null($content_stats)) {
            throw new \InvalidArgumentException('non-nullable content_stats cannot be null');
        }
        $this->container['content_stats'] = $content_stats;

        return $this;
    }

    /**
     * Gets top_source_pages
     *
     * @return object[]|null
     */
    public function getTopSourcePages()
    {
        return $this->container['top_source_pages'];
    }

    /**
     * Sets top_source_pages
     *
     * @param object[]|null $top_source_pages top_source_pages
     *
     * @return self
     */
    public function setTopSourcePages($top_source_pages)
    {
        if (is_null($top_source_pages)) {
            throw new \InvalidArgumentException('non-nullable top_source_pages cannot be null');
        }
        $this->container['top_source_pages'] = $top_source_pages;

        return $this;
    }

    /**
     * Gets top_target_pages
     *
     * @return object[]|null
     */
    public function getTopTargetPages()
    {
        return $this->container['top_target_pages'];
    }

    /**
     * Sets top_target_pages
     *
     * @param object[]|null $top_target_pages top_target_pages
     *
     * @return self
     */
    public function setTopTargetPages($top_target_pages)
    {
        if (is_null($top_target_pages)) {
            throw new \InvalidArgumentException('non-nullable top_target_pages cannot be null');
        }
        $this->container['top_target_pages'] = $top_target_pages;

        return $this;
    }

    /**
     * Gets orphaned_pages
     *
     * @return object[]|null
     */
    public function getOrphanedPages()
    {
        return $this->container['orphaned_pages'];
    }

    /**
     * Sets orphaned_pages
     *
     * @param object[]|null $orphaned_pages orphaned_pages
     *
     * @return self
     */
    public function setOrphanedPages($orphaned_pages)
    {
        if (is_null($orphaned_pages)) {
            throw new \InvalidArgumentException('non-nullable orphaned_pages cannot be null');
        }
        $this->container['orphaned_pages'] = $orphaned_pages;

        return $this;
    }

    /**
     * Gets high_performing_pages
     *
     * @return object[]|null
     */
    public function getHighPerformingPages()
    {
        return $this->container['high_performing_pages'];
    }

    /**
     * Sets high_performing_pages
     *
     * @param object[]|null $high_performing_pages high_performing_pages
     *
     * @return self
     */
    public function setHighPerformingPages($high_performing_pages)
    {
        if (is_null($high_performing_pages)) {
            throw new \InvalidArgumentException('non-nullable high_performing_pages cannot be null');
        }
        $this->container['high_performing_pages'] = $high_performing_pages;

        return $this;
    }

    /**
     * Gets most_suggested_pages
     *
     * @return object[]|null
     */
    public function getMostSuggestedPages()
    {
        return $this->container['most_suggested_pages'];
    }

    /**
     * Sets most_suggested_pages
     *
     * @param object[]|null $most_suggested_pages most_suggested_pages
     *
     * @return self
     */
    public function setMostSuggestedPages($most_suggested_pages)
    {
        if (is_null($most_suggested_pages)) {
            throw new \InvalidArgumentException('non-nullable most_suggested_pages cannot be null');
        }
        $this->container['most_suggested_pages'] = $most_suggested_pages;

        return $this;
    }

    /**
     * Gets most_linked_to_pages
     *
     * @return object[]|null
     */
    public function getMostLinkedToPages()
    {
        return $this->container['most_linked_to_pages'];
    }

    /**
     * Sets most_linked_to_pages
     *
     * @param object[]|null $most_linked_to_pages most_linked_to_pages
     *
     * @return self
     */
    public function setMostLinkedToPages($most_linked_to_pages)
    {
        if (is_null($most_linked_to_pages)) {
            throw new \InvalidArgumentException('non-nullable most_linked_to_pages cannot be null');
        }
        $this->container['most_linked_to_pages'] = $most_linked_to_pages;

        return $this;
    }

    /**
     * Gets recent_implementations
     *
     * @return \OpenAPI\Client\Model\Implementation[]|null
     */
    public function getRecentImplementations()
    {
        return $this->container['recent_implementations'];
    }

    /**
     * Sets recent_implementations
     *
     * @param \OpenAPI\Client\Model\Implementation[]|null $recent_implementations recent_implementations
     *
     * @return self
     */
    public function setRecentImplementations($recent_implementations)
    {
        if (is_null($recent_implementations)) {
            throw new \InvalidArgumentException('non-nullable recent_implementations cannot be null');
        }
        $this->container['recent_implementations'] = $recent_implementations;

        return $this;
    }

    /**
     * Gets recent_suggestions
     *
     * @return \OpenAPI\Client\Model\Suggestion[]|null
     */
    public function getRecentSuggestions()
    {
        return $this->container['recent_suggestions'];
    }

    /**
     * Sets recent_suggestions
     *
     * @param \OpenAPI\Client\Model\Suggestion[]|null $recent_suggestions recent_suggestions
     *
     * @return self
     */
    public function setRecentSuggestions($recent_suggestions)
    {
        if (is_null($recent_suggestions)) {
            throw new \InvalidArgumentException('non-nullable recent_suggestions cannot be null');
        }
        $this->container['recent_suggestions'] = $recent_suggestions;

        return $this;
    }

    /**
     * Gets recent_syncs
     *
     * @return object[]|null
     */
    public function getRecentSyncs()
    {
        return $this->container['recent_syncs'];
    }

    /**
     * Sets recent_syncs
     *
     * @param object[]|null $recent_syncs recent_syncs
     *
     * @return self
     */
    public function setRecentSyncs($recent_syncs)
    {
        if (is_null($recent_syncs)) {
            throw new \InvalidArgumentException('non-nullable recent_syncs cannot be null');
        }
        $this->container['recent_syncs'] = $recent_syncs;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


