<?php
/**
 * ProjectAnalyticsContentStats
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * RankVectors API
 *
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins.
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ProjectAnalyticsContentStats Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProjectAnalyticsContentStats implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProjectAnalytics_contentStats';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'total_pages' => 'int',
        'avg_word_count' => 'float',
        'total_words' => 'int',
        'pages_with_links' => 'int',
        'word_count_distribution' => 'object',
        'internal_link_distribution' => 'object'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'total_pages' => null,
        'avg_word_count' => null,
        'total_words' => null,
        'pages_with_links' => null,
        'word_count_distribution' => null,
        'internal_link_distribution' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'total_pages' => false,
        'avg_word_count' => false,
        'total_words' => false,
        'pages_with_links' => false,
        'word_count_distribution' => false,
        'internal_link_distribution' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'total_pages' => 'totalPages',
        'avg_word_count' => 'avgWordCount',
        'total_words' => 'totalWords',
        'pages_with_links' => 'pagesWithLinks',
        'word_count_distribution' => 'wordCountDistribution',
        'internal_link_distribution' => 'internalLinkDistribution'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'total_pages' => 'setTotalPages',
        'avg_word_count' => 'setAvgWordCount',
        'total_words' => 'setTotalWords',
        'pages_with_links' => 'setPagesWithLinks',
        'word_count_distribution' => 'setWordCountDistribution',
        'internal_link_distribution' => 'setInternalLinkDistribution'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'total_pages' => 'getTotalPages',
        'avg_word_count' => 'getAvgWordCount',
        'total_words' => 'getTotalWords',
        'pages_with_links' => 'getPagesWithLinks',
        'word_count_distribution' => 'getWordCountDistribution',
        'internal_link_distribution' => 'getInternalLinkDistribution'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('total_pages', $data ?? [], null);
        $this->setIfExists('avg_word_count', $data ?? [], null);
        $this->setIfExists('total_words', $data ?? [], null);
        $this->setIfExists('pages_with_links', $data ?? [], null);
        $this->setIfExists('word_count_distribution', $data ?? [], null);
        $this->setIfExists('internal_link_distribution', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets total_pages
     *
     * @return int|null
     */
    public function getTotalPages()
    {
        return $this->container['total_pages'];
    }

    /**
     * Sets total_pages
     *
     * @param int|null $total_pages total_pages
     *
     * @return self
     */
    public function setTotalPages($total_pages)
    {
        if (is_null($total_pages)) {
            throw new \InvalidArgumentException('non-nullable total_pages cannot be null');
        }
        $this->container['total_pages'] = $total_pages;

        return $this;
    }

    /**
     * Gets avg_word_count
     *
     * @return float|null
     */
    public function getAvgWordCount()
    {
        return $this->container['avg_word_count'];
    }

    /**
     * Sets avg_word_count
     *
     * @param float|null $avg_word_count avg_word_count
     *
     * @return self
     */
    public function setAvgWordCount($avg_word_count)
    {
        if (is_null($avg_word_count)) {
            throw new \InvalidArgumentException('non-nullable avg_word_count cannot be null');
        }
        $this->container['avg_word_count'] = $avg_word_count;

        return $this;
    }

    /**
     * Gets total_words
     *
     * @return int|null
     */
    public function getTotalWords()
    {
        return $this->container['total_words'];
    }

    /**
     * Sets total_words
     *
     * @param int|null $total_words total_words
     *
     * @return self
     */
    public function setTotalWords($total_words)
    {
        if (is_null($total_words)) {
            throw new \InvalidArgumentException('non-nullable total_words cannot be null');
        }
        $this->container['total_words'] = $total_words;

        return $this;
    }

    /**
     * Gets pages_with_links
     *
     * @return int|null
     */
    public function getPagesWithLinks()
    {
        return $this->container['pages_with_links'];
    }

    /**
     * Sets pages_with_links
     *
     * @param int|null $pages_with_links pages_with_links
     *
     * @return self
     */
    public function setPagesWithLinks($pages_with_links)
    {
        if (is_null($pages_with_links)) {
            throw new \InvalidArgumentException('non-nullable pages_with_links cannot be null');
        }
        $this->container['pages_with_links'] = $pages_with_links;

        return $this;
    }

    /**
     * Gets word_count_distribution
     *
     * @return object|null
     */
    public function getWordCountDistribution()
    {
        return $this->container['word_count_distribution'];
    }

    /**
     * Sets word_count_distribution
     *
     * @param object|null $word_count_distribution word_count_distribution
     *
     * @return self
     */
    public function setWordCountDistribution($word_count_distribution)
    {
        if (is_null($word_count_distribution)) {
            throw new \InvalidArgumentException('non-nullable word_count_distribution cannot be null');
        }
        $this->container['word_count_distribution'] = $word_count_distribution;

        return $this;
    }

    /**
     * Gets internal_link_distribution
     *
     * @return object|null
     */
    public function getInternalLinkDistribution()
    {
        return $this->container['internal_link_distribution'];
    }

    /**
     * Sets internal_link_distribution
     *
     * @param object|null $internal_link_distribution internal_link_distribution
     *
     * @return self
     */
    public function setInternalLinkDistribution($internal_link_distribution)
    {
        if (is_null($internal_link_distribution)) {
            throw new \InvalidArgumentException('non-nullable internal_link_distribution cannot be null');
        }
        $this->container['internal_link_distribution'] = $internal_link_distribution;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


